Repository hmcts/blob-router-service, pull requests merged in 2020-07, with the labels that each got.

#580 add stale blobs end point
  src/integrationTest/java/uk/gov/hmcts/reform/blobrouter/controllers/StaleBlobControllerTest.java
  src/main/java/uk/gov/hmcts/reform/blobrouter/config/ServiceConfiguration.java
  src/main/java/uk/gov/hmcts/reform/blobrouter/controllers/StaleBlobController.java
  src/main/java/uk/gov/hmcts/reform/blobrouter/model/out/BlobInfo.java
  src/main/java/uk/gov/hmcts/reform/blobrouter/model/out/SearchResult.java
  src/main/java/uk/gov/hmcts/reform/blobrouter/services/storage/StaleBlobFinder.java
  src/main/java/uk/gov/hmcts/reform/blobrouter/util/TimeUtils.java
  src/test/java/uk/gov/hmcts/reform/blobrouter/services/storage/StaleBlobFinderTest.java
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-580

#582 add bulkscanauto containers to preview
  charts/reform-scan-blob-router/values.preview.template.yaml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-582

#581 add count to search result and add test
  src/integrationTest/java/uk/gov/hmcts/reform/blobrouter/controllers/EnvelopeControllerTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/blobrouter/controllers/StaleBlobControllerTest.java
  src/main/java/uk/gov/hmcts/reform/blobrouter/controllers/EnvelopeController.java
  src/main/java/uk/gov/hmcts/reform/blobrouter/model/out/SearchResult.java
  src/main/java/uk/gov/hmcts/reform/blobrouter/util/TimeUtils.java
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-581

#583 add bulkscanauto config
  src/main/resources/application.yaml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-583

#585 disable bulkscanauto container
  src/main/resources/application.yaml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-585

#586 Revert "disable bulkscanauto (#585)"
  src/main/resources/application.yaml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-586

#588 Bump tomcat 9.0.36 -> 9.0.37
  build.gradle
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-588

#589 Added status check
  src/main/java/uk/gov/hmcts/reform/blobrouter/tasks/processors/ContainerProcessor.java
  src/test/java/uk/gov/hmcts/reform/blobrouter/tasks/processors/ContainerProcessorTest.java
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-589

#594 Review suppression file for OWASP
  config/owasp/suppressions.xml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-594

#595 Use new method signature as jenkins library is updated
  Jenkinsfile_CNP
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-595
