Repository hmcts/blob-router-service, pull requests merged in 2021-08, with the labels that each got.

#1142 DTSBPS-687: fortify integration on nightly build
  Jenkinsfile_nightly
  build.gradle
  config/fortify-client.properties
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-1142

#1143 DTSBPS-708 use-git-native-dependabot
  .dependabot/config.yml
  .github/dependabot.yml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-1143

#1144 DTSBPS-708 update depenabot config
  .github/dependabot.yml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-1144

#1150 DTSBPS-710 change queue
  build.gradle
  src/integrationTest/java/uk/gov/hmcts/reform/blobrouter/config/QueueClientConfig.java
  src/main/java/uk/gov/hmcts/reform/blobrouter/config/QueueClientConfig.java
  src/main/java/uk/gov/hmcts/reform/blobrouter/servicebus/notifications/NotificationsPublisher.java
  src/test/java/uk/gov/hmcts/reform/blobrouter/servicebus/notifications/NotificationsPublisherTest.java
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-1150

#1153 DTSBPS-712 owasp arrangements
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-1153

#1160 DTSBPS-722 fix terraform error
  infrastructure/state.tf
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-1160
