Repository hmcts/blob-router-service, pull requests merged in 2021-12, with the labels that each got.

#1259 DTSBPS-812 fix api doc
  src/main/resources/application.yaml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-1259

#1261 Bump log4j version
  build.gradle
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-1261

#1267 Updated fortify release id
  config/fortify-client.properties
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-1267
