Repository hmcts/blob-router-service, pull requests merged in 2021-06, with the labels that each got.

#1086 Removed unused method
  src/integrationTest/java/uk/gov/hmcts/reform/blobrouter/util/DateTimeUtils.java
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-1086

#1085 Ordering stale blobs
  src/main/java/uk/gov/hmcts/reform/blobrouter/services/storage/StaleBlobFinder.java
  src/test/java/uk/gov/hmcts/reform/blobrouter/services/storage/StaleBlobFinderTest.java
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-1085

#1089 remove unnecessary suppression
  config/owasp/suppressions.xml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-1089

#1090 remove unnecessary suppression
  config/owasp/suppressions.xml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-1090

#1093 DTSBPS-627 remove unnecessary jars from dependency management
  build.gradle
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-1093

#1101 fix duplicatesStrategy
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-1101

#1102 DTSBPS-636 change on success func signature for LeaseAcquirer
  src/main/java/uk/gov/hmcts/reform/blobrouter/services/storage/LeaseAcquirer.java
  src/main/java/uk/gov/hmcts/reform/blobrouter/tasks/processors/ContainerCleaner.java
  src/main/java/uk/gov/hmcts/reform/blobrouter/tasks/processors/ContainerProcessor.java
  src/main/java/uk/gov/hmcts/reform/blobrouter/tasks/processors/RejectedContainerCleaner.java
  src/test/java/uk/gov/hmcts/reform/blobrouter/services/storage/LeaseAcquirerTest.java
  src/test/java/uk/gov/hmcts/reform/blobrouter/tasks/processors/ContainerProcessorTest.java
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-1102

#1107 Update DockerImage to new tagging reference
  Jenkinsfile_CNP
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-1107

#1110 DTSBPS-650 upgrade java chart
  charts/reform-scan-blob-router/Chart.yaml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-1110
