Repository hmcts/blob-router-service, pull requests merged in 2022-04, with the labels that each got.

#1377 Suppressed vulnerability
  config/owasp/suppressions.xml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-1377

#1383 Suppress vulnerability
  config/owasp/suppressions.xml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-1383

#1388 Upgrade spring boot version
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-1388

#1399 Suppressed vulnerability
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-1399

#1401 Add additional ingres
  charts/reform-scan-blob-router/Chart.yaml
  charts/reform-scan-blob-router/values.yaml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-1401
