Repository hmcts/blob-router-service, pull requests merged in 2022-07, with the labels that each got.

#1516 Suppressed CVE-2022-33915
  config/owasp/suppressions.xml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-1516

#1534 Suppress CVE-2022-31569
  config/owasp/suppressions.xml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-1534

#1535 Bump java chart version
  charts/reform-scan-blob-router/Chart.yaml
  charts/reform-scan-blob-router/values.preview.template.yaml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-1535

#1540 DTSBPS-1020: Pinned azureem version
  infrastructure/state.tf
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-1540
