Repository hmcts/blob-router-service, pull requests merged in 2022-06, with the labels that each got.

#1469 DTSBPS-960: Suppress CVE-2022-22976
  config/owasp/suppressions.xml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-1469

#1477 DTSBPS-978: Suppressed CVE-2022-22978
  config/owasp/suppressions.xml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-1477

#1478 DTSBPS-978: Fix CVE-2022-22978
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-1478

#1513 Suppressed CVE
  config/owasp/suppressions.xml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-1513
