Repository hmcts/blob-router-service, pull requests merged in 2022-11, with the labels that each got.

#1724 Fix CVE and suppress spring-security vulnerabilities (DTSBPS-1143)
  config/owasp/suppressions.xml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-1724

#1726 Fix Github actions build (DTSBPS-1147)
  .github/workflows/ci.yml
  .github/workflows/swagger.yml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-1726

#1727 Revert "Fix Github actions build (DTSBPS-1147)"
  .github/workflows/ci.yml
  .github/workflows/swagger.yml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-1727

#1742 Cleanup suppressions (DTSBPS-1141)
  config/owasp/suppressions.xml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-1742

#1759 DTSBPS-1163: Suppress CVE-2016-1000027
  config/owasp/suppressions.xml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-1759

#1762 DTSBPS-1167: Suppress CVE-2022-29885
  config/owasp/suppressions.xml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-1762
