Repository hmcts/blob-router-service, pull requests merged in 2022-05, with the labels that each got.

#1413 Fix CVE-2022-24823 (DTSBPS-943)
  build.gradle
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-1413

#1414 Suppress CVE-2016-1000027
  config/owasp/suppressions.xml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-1414

#1416 Suppress CVE-2022-29885
  config/owasp/suppressions.xml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-1416

#1432 Bump Spring dependencies
  build.gradle
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-1432
