Repository hmcts/blob-router-service, pull requests merged in 2022-08, with the labels that each got.

#1568 DTSBPS-985: Add actions-api-key
  charts/reform-scan-blob-router/Chart.yaml
  charts/reform-scan-blob-router/values.aat.template.yaml
  charts/reform-scan-blob-router/values.preview.template.yaml
  charts/reform-scan-blob-router/values.yaml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-1568

#1569 DTSBPS-985: Added authHeader
  src/integrationTest/java/uk/gov/hmcts/reform/blobrouter/controllers/ActionControllerTest.java
  src/integrationTest/resources/application.properties
  src/main/java/uk/gov/hmcts/reform/blobrouter/controllers/ActionController.java
  src/main/resources/application.yaml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-1569

#1577 Fix github actions
  .github/workflows/ci.yml
  .github/workflows/swagger.yml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-1577

#1576 DTSBPS-985: Introduced AuthValidator
  src/main/java/uk/gov/hmcts/reform/blobrouter/controllers/ActionController.java
  src/main/java/uk/gov/hmcts/reform/blobrouter/reconciliation/controller/ReconciliationController.java
  src/main/java/uk/gov/hmcts/reform/blobrouter/reconciliation/controller/ReconciliationReportGenerationController.java
  src/main/java/uk/gov/hmcts/reform/blobrouter/util/AuthValidator.java
  src/test/java/uk/gov/hmcts/reform/blobrouter/util/AuthValidatorTest.java
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-1576

#1596 Suppress CVE-2016-1000027
  config/owasp/suppressions.xml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-1596

#1598 Suppress CVE-2022-29885
  config/owasp/suppressions.xml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-1598

#1599 Add backstage configuration file
  catalog-info.yaml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-1599
