Repository hmcts/blob-router-service, pull requests merged in 2023-01, with the labels that each got.

#1842 DTSBPS-1235: Suppressed CVE-2021-4277
  config/owasp/suppressions.xml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-1842

#1848 DTSBPS-1236: Suppressed dependencies
  config/owasp/suppressions.xml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-1848

#1867 DTSBPS-1248: Fix docker build
  Dockerfile
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-1867

#1886 DTSBPS-1258: Upgraded AppInsights
  Dockerfile
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-1886
