Repository hmcts/blob-router-service, pull requests merged in 2024-11, with the labels that each got.

#2300 update packages
  build.gradle
  infrastructure/.terraform-version
Labels: ns:reform-scan, prd:reform-scan, prod/add-or-update, aat/add-or-update, rel:reform-scan-blob-router-pr-2300

#2305 FACT-2003 - updates azure and azurite
  build.gradle
  src/integrationTest/java/uk/gov/hmcts/reform/blobrouter/util/BlobStorageBaseTest.java
  src/integrationTest/resources/docker-compose.yml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-2305

#2311 enable trace logs once more for demo etc
  lib/applicationinsights.json
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-2311
