Repository hmcts/blob-router-service, pull requests merged in 2024-08, with the labels that each got.

#2245 FACT-1873 Private Law Onboarding Phase 2: Enable Private Law
  charts/reform-scan-blob-router/Chart.yaml
  charts/reform-scan-blob-router/values.yaml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-2245

#2246 FACT-1809 custom APIM logging
  infrastructure/aat.tfvars
  infrastructure/cft-api-mgmt-logging.tf
  infrastructure/demo.tfvars
  infrastructure/perftest.tfvars
  infrastructure/prod.tfvars
  infrastructure/variables.tf
Labels: ns:reform-scan, prd:reform-scan, prod/add-or-update, aat/add-or-update, rel:reform-scan-blob-router-pr-2246

#2249 Updated providers
  infrastructure/cft-api-mgmt-logging.tf
  infrastructure/main.tf
Labels: prod/add-or-update, aat/add-or-update

#2251 cftapps provider
  infrastructure/main.tf
Labels: prod/add-or-update, aat/add-or-update

#2248 FACT-1906 updated dependancies
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
Labels: ns:reform-scan, prd:reform-scan, prod/add-or-update, aat/add-or-update, rel:reform-scan-blob-router-pr-2248

#2258 Remove db image in compose
  docker-compose.yml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-2258

#2257 FACT-1703 - Update Azure Storage Blob
  build.gradle
  config/owasp/suppressions.xml
  src/integrationTest/java/uk/gov/hmcts/reform/blobrouter/controllers/SasTokenControllerExceptionTest.java
  src/main/java/uk/gov/hmcts/reform/blobrouter/services/storage/SasTokenCache.java
Labels: ns:reform-scan, prd:reform-scan, prod/add-or-update, aat/add-or-update, rel:reform-scan-blob-router-pr-2257
