Repository hmcts/blob-router-service, pull requests merged in 2024-09, with the labels that each got.

#2261 FACT-1817 Removed old APIM
  infrastructure/api-mgmt.tf
  infrastructure/api-policy.xml
Labels: ns:reform-scan, prd:reform-scan, aat/destroy, prod/destroy, rel:reform-scan-blob-router-pr-2261

#2262 Update smoketests
  Jenkinsfile_CNP
  README.md
  infrastructure/aat.tfvars
  infrastructure/api-test-vars.tf
  infrastructure/cft-api-mgmt.tf
  src/smokeTest/java/uk/gov/hmcts/reform/blobrouter/GetSasTokenTest.java
  src/smokeTest/java/uk/gov/hmcts/reform/blobrouter/ReconciliationApiTest.java
  src/smokeTest/resources/application.conf
Labels: ns:reform-scan, prd:reform-scan, aat/add-or-update, prod/destroy, rel:reform-scan-blob-router-pr-2262

#2264 adding privatelaw for reform and bulk scan
  .gitignore
  docker/storage/init-azurite.sh
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-2264

#2265 FACT-1976 - CVE Updates Sept
  build.gradle
  charts/reform-scan-blob-router/Chart.yaml
  config/owasp/suppressions.xml
  infrastructure/cft-api-mgmt.tf
  infrastructure/state.tf
Labels: ns:reform-scan, prd:reform-scan, prod/add-or-update, aat/add-or-update, rel:reform-scan-blob-router-pr-2265

#2276 FACT-1890 fix func test lines
  src/functionalTest/java/uk/gov/hmcts/reform/blobrouter/RejectedEnvelopesNotificationTest.java
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-2276

#2268 FACT-1797 java 17 to 21
  .github/workflows/ci.yml
  .github/workflows/publish-openapi.yaml
  Dockerfile
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  src/test/resources/application.yaml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-blob-router-pr-2268

#2278 FACT-1995 New APIM
  infrastructure/api-mgmt-logging.tf
  infrastructure/api-mgmt-policy.xml
  infrastructure/api-mgmt.tf
  infrastructure/cft-api-mgmt.tf
  infrastructure/main.tf
Labels: ns:reform-scan, prd:reform-scan, prod/add-or-update, aat/add-or-update, rel:reform-scan-blob-router-pr-2278

#2279 FACT-1995 Update providers, depends_on
  infrastructure/api-mgmt-logging.tf
  infrastructure/api-mgmt.tf
  infrastructure/main.tf
  infrastructure/providers.tf
Labels: ns:reform-scan, prd:reform-scan, prod/add-or-update, aat/add-or-update, rel:reform-scan-blob-router-pr-2279

#2280 Temp comment out infra
  infrastructure/api-mgmt-logging.tf
  infrastructure/api-mgmt.tf
Labels: ns:reform-scan, prd:reform-scan, prod/add-or-update, aat/add-or-update, rel:reform-scan-blob-router-pr-2280

#2281 APIM POC
  infrastructure/api-mgmt.tf
Labels: ns:reform-scan, prd:reform-scan, prod/add-or-update, aat/add-or-update, rel:reform-scan-blob-router-pr-2281

#2282 FACT-1995 updated
  infrastructure/api-mgmt-policy.xml
  infrastructure/api-mgmt.tf
Labels: ns:reform-scan, prd:reform-scan, prod/add-or-update, aat/add-or-update, rel:reform-scan-blob-router-pr-2282

#2283 update versions
  infrastructure/.terraform-version
  infrastructure/providers.tf
Labels: ns:reform-scan, prd:reform-scan, prod/add-or-update, aat/add-or-update, rel:reform-scan-blob-router-pr-2283

#2284 Temp comment out
  infrastructure/api-mgmt.tf
Labels: ns:reform-scan, prd:reform-scan, prod/add-or-update, aat/add-or-update, rel:reform-scan-blob-router-pr-2284

#2285 Add api
  infrastructure/api-mgmt.tf
Labels: ns:reform-scan, prd:reform-scan, prod/add-or-update, aat/add-or-update, rel:reform-scan-blob-router-pr-2285

#2286 disable sub
  infrastructure/api-mgmt.tf
Labels: ns:reform-scan, prd:reform-scan, prod/add-or-update, aat/add-or-update, rel:reform-scan-blob-router-pr-2286

#2287 remove priv
  infrastructure/api-mgmt.tf
Labels: ns:reform-scan, prd:reform-scan, prod/add-or-update, aat/add-or-update, rel:reform-scan-blob-router-pr-2287

#2289 apim debug
  infrastructure/api-mgmt.tf
Labels: ns:reform-scan, prd:reform-scan, prod/add-or-update, aat/add-or-update, rel:reform-scan-blob-router-pr-2289

#2290 Re-add correct url
  infrastructure/api-mgmt.tf
Labels: ns:reform-scan, prd:reform-scan, prod/add-or-update, aat/add-or-update, rel:reform-scan-blob-router-pr-2290

#2291 new rev
  infrastructure/api-mgmt.tf
Labels: ns:reform-scan, prd:reform-scan, aat/destroy, prod/destroy, rel:reform-scan-blob-router-pr-2291

#2293 updated
  infrastructure/api-mgmt-policy.xml
Labels: ns:reform-scan, prd:reform-scan, prod/add-or-update, aat/add-or-update, rel:reform-scan-blob-router-pr-2293
